# This is a basic workflow that only runs on schedule

name: retrieve_data

#on:
#  schedule:
#    - cron: '0 9 * * *'


# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job
  run_thingy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # retrieve secrets from github
    env:
        apikey: ${{ secrets.APIKEY}}
        apisecretkey: ${{ secrets.APISECRETKEY}}
        access_token: ${{ secrets.ACCESS_TOKEN}}
        access_token_secret: ${{ secrets.ACCESS_TOKEN_SECRET}}
    #
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #install ubuntu packages
      - name: install ssl
        run: sudo apt-get install -y --no-install-recommends libcurl4-openssl-dev curl
      - uses: actions/checkout@master
      - name: setup-r
        uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.1.1'
      - name: required packages  
        run: Rscript -e "install.packages('dplyr')"
        run: Rscript -e "install.packages('tidyr')"
        run: Rscript -e "install.packages('readr')"
        run: Rscript -e "install.packages('purrr')"
        run: Rscript -e "install.packages('tibble')"
        run: Rscript -e "install.packages('stringr')"
        run: Rscript -e "install.packages('forcats')"
        run: Rscript -e "install.packages('magrittr')"
        run: Rscript -e "install.packages('lubridate')"
        run: Rscript -e "install.packages('fs')"

      # execute Rscript
      - name: run retriever
        run: Rscript retrieve/data_retriever.R
      #commit file           
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "add data"
          git push 
